// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace Projekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503180713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Projekt.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackName", "CardNumber")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNumber = "001",
                            Name = "BLUBERINI OCTOPUSINI",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 2,
                            CardNumber = "002",
                            Name = "TIRILICALICA TIRILICALACO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 3,
                            CardNumber = "003",
                            Name = "COCCODRILLO FORMAGGIOSO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 4,
                            CardNumber = "004",
                            Name = "PANBRONCIO AL LATTE",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 5,
                            CardNumber = "005",
                            Name = "MARCO POLLO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 6,
                            CardNumber = "006",
                            Name = "OCA DEL ROVER LUNARE",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 7,
                            CardNumber = "007",
                            Name = "GANGSTER FOOTERA",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 8,
                            CardNumber = "008",
                            Name = "CACTO IPPOPOTAMO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 9,
                            CardNumber = "009",
                            Name = "RAPARRAPA CHE PARA",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 10,
                            CardNumber = "010",
                            Name = "CERVELLO PUDDING",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 11,
                            CardNumber = "011",
                            Name = "GNAMMO SLAMMO E SGOMMO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 12,
                            CardNumber = "012",
                            Name = "AEROMUCCA ARMATA",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 13,
                            CardNumber = "013",
                            Name = "CAPRAMPANTE SOTTOPANCA",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 14,
                            CardNumber = "014",
                            Name = "FRULLI FRULLA",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 15,
                            CardNumber = "015",
                            Name = "CROCODILO POTATINO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 16,
                            CardNumber = "016",
                            Name = "BONECA AMBALABU",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 17,
                            CardNumber = "017",
                            Name = "TRIPPA TROPPA TRALALA LIRI LIRÀ TUNG TUNG SAHUR BONECA TUNG TUNG TRALALELO TRIPPI TROPPA CROCODINA",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 18,
                            CardNumber = "018",
                            Name = "RUGGINATO LUPOGT",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 19,
                            CardNumber = "019",
                            Name = "BALLERINO LOLOLO",
                            PackName = "brainrot"
                        },
                        new
                        {
                            Id = 20,
                            CardNumber = "020",
                            Name = "LA VACCA ATOMO ATOMITA",
                            PackName = "brainrot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
